=== cadams4341/hyde/023_Data_Acquisition_Prototype/XMLResource/Prototype-004.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="PatientData" type="PatientDataType" />

    <xsd:complexType name="PatientDataType">
        <xsd:sequence>
            <xsd:element minOccurs="1" maxOccurs="1" name="Device" 
                         type="DeviceDataType" />
		 <xsd:element minOccurs="1" maxOccurs="unbounded" 
			 name="CalculatedDataSet" 
                         type="CalculatedDataSetType" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="DeviceDataType">
        <xsd:sequence>
            <xsd:element minOccurs="1" maxOccurs="1" name="DeviceType" 
                         type="xsd:string" />
            <xsd:element minOccurs="1" maxOccurs="1" name="DeviceID" 
                         type="xsd:string" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CalculatedDataSetType">
            <xsd:sequence>
                <xsd:element minOccurs="1" maxOccurs="1" 
			name="DateTimeStamp" 
			type="xsd:dateTime"/>
                <xsd:element minOccurs="0" maxOccurs="1" 
			name="SystolicBloodPressure" 
			type="xsd:integer"/>
                <xsd:element minOccurs="0" maxOccurs="1" 
			name="DiastolicBloodPressure" 
			type="xsd:integer"/>
                <xsd:element minOccurs="0" maxOccurs="1" 
			name="HeartRate" 
			type="xsd:integer"/>
                <xsd:element maxOccurs="1" minOccurs="1" 
                             name="DataQuality" type="DataQualityType"/>
            </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="DataQualityType">
        <xsd:restriction base="xsd:integer">
            <xsd:minInclusive value="1"  fixed="true" />
            <xsd:maxInclusive value="10" fixed="true" />
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== cadams4341/hyde/023_Data_Acquisition_Prototype/XMLResource/Prototype-004.xml
<?xml version="1.0" encoding="UTF-8"?>
<PatientData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Prototype-004.xsd">
    <Device>
       <DeviceType>PHX-prototype-1c</DeviceType>
       <DeviceID>PHX-0834-872</DeviceID>
    </Device>
    <CalculatedDataSet>
       <DateTimeStamp> 2008-08-06T09:34:01 </DateTimeStamp>
       <SystolicBloodPressure> 134 </SystolicBloodPressure>
       <DiastolicBloodPressure> 83 </DiastolicBloodPressure>
       <HeartRate> 81 </HeartRate>
       <DataQuality> 10 </DataQuality>
    </CalculatedDataSet>
    <CalculatedDataSet>
       <DateTimeStamp> 2008-08-06T10:07:03 </DateTimeStamp>
       <SystolicBloodPressure> 130 </SystolicBloodPressure>
       <DiastolicBloodPressure> 81 </DiastolicBloodPressure>
       <HeartRate> 78 </HeartRate>
       <DataQuality> 10 </DataQuality>
    </CalculatedDataSet>
    <CalculatedDataSet>
       <DateTimeStamp> 2008-08-06T10:41:07 </DateTimeStamp>
       <SystolicBloodPressure> 138 </SystolicBloodPressure>
       <DiastolicBloodPressure> 88 </DiastolicBloodPressure>
       <HeartRate> 84 </HeartRate>
       <DataQuality> 9 </DataQuality>
    </CalculatedDataSet>
    <CalculatedDataSet>
       <DateTimeStamp> 2008-08-06T11:12:40 </DateTimeStamp>
       <SystolicBloodPressure> 138 </SystolicBloodPressure>
       <HeartRate> 84 </HeartRate>
       <DataQuality> 5 </DataQuality>
    </CalculatedDataSet>
    <CalculatedDataSet>
       <DateTimeStamp> 2008-08-06T11:41:54 </DateTimeStamp>
       <HeartRate> 89 </HeartRate>
       <DataQuality> 2 </DataQuality>
    </CalculatedDataSet>
</PatientData>
